services:
  website:
    build: .
    ports:
      - "2180:4321"
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 4321
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./src
          ignore:
            - node_modules/
